{% set version = "4.0.5" %}

package:
  name: gitdb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gitdb/gitdb-{{ version }}.tar.gz
  sha256: c9e1f2d0db7ddb9a704c2a0217be31214e91a4fe1dea1efad19ae42ba0c285c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - smmap >=3.0.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - gitdb
    - gitdb.db

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Git Object Database

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
