{% set version = "4.0.10" %}

package:
  name: gitdb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gitdb/gitdb-{{ version }}.tar.gz
  sha256: 6eb990b69df4e15bad899ea868dc46572c3f75339735663b81de79b06f17eb9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - smmap >=3.0.1,<6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - gitdb
    - gitdb.db

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Git Object Database

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - xhochy
